# Site Configuration
title: Raiders of the Serpent Sea
email: rotss-dnd@cle.ar.it
baseurl: ""
url: "https://dndaux.de"
description: >-
  A D&D campaign blog following the adventures of our party as they 
  navigate treacherous waters and uncover ancient mysteries.

# Social & Contact
github_username: wayneoween

# Theme Settings
remote_theme: sylhare/Type-on-Strap
color_theme: auto
header_text: Adventures in cold waters
header_feature_image: assets/images/header.jpg
header_feature_image_responsive: false

# Content & Navigation
permalink: /:title/
excerpt: true
post_navigation: true

# Pagination
paginate: 10
paginate_path: "/page:num"

# Features
cookie_consent: false

# Build Settings
plugins:
  - jekyll-feed
  - jekyll-glossary_tooltip
  - jekyll-paginate
  - jekyll-seo-tag

sass:
  style: compressed
  quiet_deps: true
  silence_deprecations:
    - import

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
