backend:
  name: github
  repo: wayneoween/dndaux.de
  branch: main

# Enable local backend when running locally
local_backend: true

# Site settings
site_url: http://localhost:4000
display_url: http://localhost:4000
logo_url: /assets/images/logo.png

# Media settings
media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

# Collection definitions
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} - {{date | date('YYYY-MM-DD')}}"
    sortable_fields: ['title', 'date']
    view_filters:
      - label: "Drafts"
        field: "draft"
        pattern: true
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { 
          label: "Categories", 
          name: "categories", 
          widget: "string", 
          required: false,
          hint: "Comma-separated list of categories"
        }
      - { 
          label: "Background Image", 
          name: "background", 
          widget: "image", 
          required: false,
          allow_multiple: false,
          choose_url: true,
          hint: "Featured image for the post"
        }
      - { 
          label: "Draft", 
          name: "draft", 
          widget: "boolean", 
          required: false, 
          default: false,
          hint: "Set to true to save as draft"
        }
      - { 
          label: "Body", 
          name: "body", 
          widget: "markdown",
          buttons: ["bold", "italic", "code", "link", "heading-one", "heading-two", "heading-three", "quote", "bulleted-list", "numbered-list"],
          editor_components: ["image", "code-block"]
        }

  - name: "pages"
    label: "Pages"
    folder: "/"
    create: true
    filter: {field: "layout", value: "page"}
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string", hint: "Path for the page, e.g., /about/" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "glossary"
    label: "Glossary"
    files:
      - label: "Glossary Terms"
        name: "glossary"
        file: "_data/glossary.yml"
        fields:
          - label: "Terms"
            name: "terms"
            widget: "list"
            summary: "{{term}} - {{definition}}"
            fields:
              - {label: "Term", name: "term", widget: "string"}
              - {label: "Definition", name: "definition", widget: "text"}
              - {label: "Reference URL", name: "url", widget: "string", required: false}
              - {label: "Image", name: "image", widget: "image", required: false, hint: "Character/creature/item image"}
              - {label: "Image Alt Text", name: "image_alt", widget: "string", required: false, hint: "Description for accessibility"}